<?php
require_once 'functions.php';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Use - Vrissiana Beach Hotel Protaras, Cyprus</title>

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <!-- partial -->

    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Raleway|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/CSS/style.css">
</head>

<body>
    <!-- navigation bar -->
    <?php navigation_bar(); ?>
    <!-- /BACKROUND IMAGE -->
    <section class="header">
        <div class="box-header">
            <img src="https://www.tsokkos.com/images/details/others_banner.jpg" alt="Rocks and the sea" class="back-img">
        </div>
    </section>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.php">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Terms &amp; Condition</li>
        </ol>
    </nav>

    <section class="box-term-of-use">
        <h1>Terms &amp; Condition</h1>
        <div class="container-term-of-use">
            <h2>PLEASE READ THESE TERMS AND CONDITION CAREFULLY BEFORE USING THIS SITE:</h2>

            <p>By using this site, you signify your assent to these terms of use. If you do not agree to these terms of use, please do not use the site.</p>

            <p> Please note that A. Tsokkos Hotels Public Ltd will appear on your bank statement for any processed payment.</p>
            <h2> RESTRICTIONS ON USE OF MATERIALS</h2>

            <p> This site is owned and operated by A. Tsokkos Hotels Public Ltd. (referred to as "Tsokkos Hotels," "we," "us," or "our" herein). No material from the site may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, except that you may download one copy of the materials on any single computer for your non-commercial use only, provided that you keep intact all copyright and other proprietary notices. Modification of the materials or use of the materials for any other purpose is a violation of copyright and other proprietary rights. The use of any such material on any other Web site or networked computer environment is prohibited. Except as otherwise indicated on this site and except for the trademarks, service marks and trade names of other companies that are displayed on this site, all trademarks, service marks and trade names are proprietary to Tsokkos Hotels. In the event that you download any software from the site, the software, including any files, images incorporated in or generated by the software, and data accompanying the software (collectively, the "Software") are non-exclusively licensed to you by Tsokkos Hotels. Tsokkos Hotels does not transfer title to the Software to you. Tsokkos Hotels retains full and complete title to the Software, and all intellectual property rights therein. You may not redistribute, sell, decompile, reverse engineer, disassemble, or otherwise reduce the Software to a human-perceivable form.</p>
            <h2> DISCLAIMER</h2>

            <p> The materials in this site are provided "as is" and without warranties of any kind either express or implied. To the fullest extent permissible pursuant to applicable law, Tsokkos Hotels disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. Tsokkos Hotels does not warrant that the functions contained in the materials will be uninterrupted or error-free, that defects will be corrected, or that this site or the server that makes it available are free of viruses or other harmful components. Tsokkos Hotels does not warrant or make any representations regarding the use or the results of the use of the materials in this site in terms of their correctness, accuracy, reliability, or otherwise. You (and not Tsokkos Hotels) assume the entire cost of all necessary servicing, repair, or correction. Applicable law may not allow the exclusion of implied warranties, so the above exclusion may not apply to you.</p>
            <h2> LIMITATION OF LIABILITY</h2>

            <p> Under no circumstances, including, but not limited to, negligence, shall Tsokkos Hotels be liable for any special or consequential damages that result from the use of, or the inability to use, the materials in this site, even if Tsokkos Hotels or a Tsokkos Hotels authorized representative has been advised of the possibility of such damages. In no event shall Tsokkos Hotels have any liability to you for damages, losses and causes of action (whether in contract, tort (including, but not limited to, negligence), or otherwise) for accessing this site.</p>
            <h2> OTHER</h2>

            <p> All claims, disputes or disagreements which may arise out of the interpretation, performance or in any way relating to your use of this site and any and all other Tsokkos Hotels site(s), shall be submitted exclusively to the jurisdiction of the courts located in the Country of Cyprus, and the city of Nicosia.</p>

        </div>
    </section>
<?php footer();?>
</body>

</html>